### ISSUE TITLE
SystemExit prevents traceback and stops test execution

### ISSUE THREAD

**Issue by krisztianfekete** [testing-cabal/testtools#144]
I got this behavior during a test run and was left without diagnostic output (i.e. traceback, stdout, stderr).
(there the `SystemExit` was raised by `argparse` due to a yet non-existing subcommand)

Running this code

```python
# test.py
import unittest
import testtools

class Test_testtools(testtools.TestCase):
    def test_1(self):
        pass

    def test_2(self):
        raise SystemExit(0)

    def test_3(self):
        pass

if __name__ == '__main__':
    unittest.main()
```

produces the following output:

```sh
$ python test.py
.E$ 
```

or with verbose on:

```sh
$ python test.py -v
test_1 (__main__.Test_testtools)
__main__.Test_testtools.test_1 ... ok
test_2 (__main__.Test_testtools)
__main__.Test_testtools.test_2 ... ERROR
$ echo $?
0
```

Note, that the third test was not run at all and there was no traceback nor a `FAILED` notification.
The exit status was 0.

When I run the tests with testtools' runner I get this:

```sh
$ python -m testtools.run test.py
Tests running...
======================================================================
ERROR: test.Test_testtools.test_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 10, in test_2
    raise SystemExit(0)
SystemExit: 0
Ran 2 tests in 0.001s
FAILED (failures=1)
$ echo $?
0
```
only two tests run, there is a traceback, but exit status is still 0!

**Comment by rbtcollins** [comment]
Hmm, the exit of testing etc is correct, but the status of 0 is something we can probably fix.

**Comment by krisztianfekete** [comment]
Exit of testing is breaking tradition with the unittest family (see below).

Why?

---- 

`unittest`'s runner do not exit on `SystemExit` (nor does `unittest2`): 

```python
# test.py
import unittest

class Test(unittest.TestCase):
    def test_1(self):
        pass

    def test_2(self):
        raise SystemExit(0)

    def test_3(self):
        pass

if __name__ == '__main__':
    unittest.main()
```

produces

```sh
$ python test.py
.E.
======================================================================
ERROR: test_2 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 9, in test_2
    raise SystemExit(0)
SystemExit: 0
----------------------------------------------------------------------
Ran 3 tests in 0.001s
FAILED (errors=1)
$ echo $?
1
```

The exit is at least suprising enough to challenge test runners - the problematic test in the description has surprising results when run with `unittest`, `unittest2`,  `green` and `nose`.
The first three produce no traceback at all and die with a zero status!
`nose` is helpful, though it confusingly produces two `E`-s instead of one and two different tracebacks, but dies correctly with non-zero status (1).

**Comment by thomir** [comment]
FWIW, I've also been bitten by this in the past, and I also think testtools should convert a raised SystemExit into a test error. Unit tests should never raise SystemExit.

...but @rbtcollins  and I have had this conversation before :D

**Comment by krisztianfekete** [comment]
@thomir I could not find your conversation.

I found these however:

- [Tests raising SystemExit should be reported rather than silently disappearing even in non-verbose mode](https://bugs.launchpad.net/launchpad/+bug/647355)
- [tests that call sys.exit(0) appear to pass](https://bugs.launchpad.net/testtools/+bug/1364188)
  - merged fix: [Fix handling of uncatchable exceptions. #104](https://github.com/testing-cabal/testtools/pull/104)

In the exit status case it looks like a regression.

As for exiting: I can accept an exit only if a traceback is printed immediately to stderr: one of the test framework's tasks is to help locating/diagnosing problems.  It clearly do not happen in unittest, unittest2, green if using testtools, while they do print a traceback without it.

**Comment by rbtcollins** [comment]
Possibly insufficiently robust fixing; I'll poke around that in a bit. The test process should never exit 0 if the test suite exited due to an exception escaping execution.

**Comment by wallrj** [comment]
I found this bug on Launchpad too: https://bugs.launchpad.net/launchpad/+bug/647355
