### ISSUE TITLE
Test suite fails for Python 2.7.10

### ISSUE THREAD

**Issue by warsaw** [testing-cabal/testtools#150]
`make PYTHON=python2.7 check` fails for me with the current git head and Python 2.7.10.  It passes for me with python3.4 and python3.5.  All are using the Ubuntu Python packages.

```
% make PYTHON=python2.7 check
PYTHONPATH=/home/barry/projects/debian/testtools/upstream python2.7 -m testtools.run testtools.tests.test_suite
Tests running...
Unhandled error in Deferred:


Traceback (most recent call last):
  File "testtools/runtest.py", line 108, in _run_prepared_result
    self._run_core()
  File "testtools/runtest.py", line 144, in _run_core
    self.case._run_test_method, self.result):
  File "testtools/runtest.py", line 191, in _run_user
    return fn(*args, **kwargs)
  File "testtools/testcase.py", line 654, in _run_test_method
    return self._get_test_method()()
--- <exception caught here> ---
  File "testtools/tests/test_deferredruntest.py", line 792, in test_assert_fails_with_expected_exception
    1/0
exceptions.ZeroDivisionError: integer division or modulo by zero
Unhandled error in Deferred:


Traceback (most recent call last):
  File "testtools/runtest.py", line 144, in _run_core
    self.case._run_test_method, self.result):
  File "testtools/runtest.py", line 191, in _run_user
    return fn(*args, **kwargs)
  File "testtools/testcase.py", line 654, in _run_test_method
    return self._get_test_method()()
  File "testtools/tests/test_deferredruntest.py", line 773, in test_assert_fails_with_wrong_exception
    defer.maybeDeferred(lambda: 1/0), RuntimeError, KeyboardInterrupt)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "testtools/tests/test_deferredruntest.py", line 773, in <lambda>
    defer.maybeDeferred(lambda: 1/0), RuntimeError, KeyboardInterrupt)
exceptions.ZeroDivisionError: integer division or modulo by zero
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAssertFailsWith.test_assert_fails_with_expected_exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 795, in test_assert_fails_with_expected_exception
    d = assert_fails_with(defer.fail(f), ZeroDivisionError)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAssertFailsWith.test_assert_fails_with_success
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 743, in test_assert_fails_with_success
    d = assert_fails_with(defer.succeed(marker), RuntimeError)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAssertFailsWith.test_assert_fails_with_success_multiple_types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 758, in test_assert_fails_with_success_multiple_types
    defer.succeed(marker), RuntimeError, ZeroDivisionError)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAssertFailsWith.test_assert_fails_with_wrong_exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 773, in test_assert_fails_with_wrong_exception
    defer.maybeDeferred(lambda: 1/0), RuntimeError, KeyboardInterrupt)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAssertFailsWith.test_custom_failure_exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 806, in test_custom_failure_exception
    failureException=CustomException)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_async_cleanups
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 368, in test_async_cleanups
    runner = self.make_runner(test, timeout)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_calls_setUp_test_tearDown_in_sequence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 319, in test_calls_setUp_test_tearDown_in_sequence
    runner = self.make_runner(test, timeout)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_clean_reactor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 381, in test_clean_reactor
    runner = self.make_runner(test, timeout)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_convenient_construction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 523, in test_convenient_construction
    factory = AsynchronousDeferredRunTest.make_factory(reactor, timeout)
AttributeError: 'NoneType' object has no attribute 'make_factory'
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_convenient_construction_default_debugging
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 569, in test_convenient_construction_default_debugging
    factory = AsynchronousDeferredRunTest.make_factory(debug=True)
AttributeError: 'NoneType' object has no attribute 'make_factory'
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_convenient_construction_default_reactor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 546, in test_convenient_construction_default_reactor
    factory = AsynchronousDeferredRunTest.make_factory(reactor=reactor)
AttributeError: 'NoneType' object has no attribute 'make_factory'
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_convenient_construction_default_timeout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 558, in test_convenient_construction_default_timeout
    factory = AsynchronousDeferredRunTest.make_factory(timeout=timeout)
AttributeError: 'NoneType' object has no attribute 'make_factory'
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_debugging_enabled_during_test_with_debug_flag
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 726, in test_debugging_enabled_during_test_with_debug_flag
    debug=True)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_debugging_unchanged_during_test_by_default
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 711, in test_debugging_unchanged_during_test_by_default
    reactor=self.make_reactor(), timeout=self.make_timeout())
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_deferred_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 580, in test_deferred_error
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_exports_reactor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 401, in test_exports_reactor
    runner = self.make_runner(test, timeout)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_fast_keyboard_interrupt_stops_test_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 492, in test_fast_keyboard_interrupt_stops_test_run
    runner = self.make_runner(test, timeout * 5)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_keyboard_interrupt_stops_test_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 473, in test_keyboard_interrupt_stops_test_run
    runner = self.make_runner(test, timeout * 5)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_log_err_flushed_is_success
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 669, in test_log_err_flushed_is_success
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_log_err_is_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 638, in test_log_err_is_error
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_log_in_details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 690, in test_log_in_details
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_only_addError_once
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 608, in test_only_addError_once
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_setUp_returns_deferred_that_fires_later
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 286, in test_setUp_returns_deferred_that_fires_later
    runner = self.make_runner(test, timeout=timeout)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_timeout_causes_test_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 505, in test_timeout_causes_test_error
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_unhandled_error_from_deferred
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 417, in test_unhandled_error_from_deferred
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_unhandled_error_from_deferred_combined_with_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 444, in test_unhandled_error_from_deferred_combined_with_error
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 262, in make_runner
    test, test.exception_handlers, timeout=timeout)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestAsynchronousDeferredRunTest.test_use_convenient_factory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 532, in test_use_convenient_factory
    factory = AsynchronousDeferredRunTest.make_factory()
AttributeError: 'NoneType' object has no attribute 'make_factory'
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestRunWithLogObservers.test_restores_observers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 819, in test_restores_observers
    from testtools.deferredruntest import run_with_log_observers
  File "testtools/deferredruntest.py", line 31, in <module>
    from twisted.trial.unittest import _LogObserver
ImportError: cannot import name _LogObserver
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestSynchronousDeferredRunTest.test_failure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 222, in test_failure
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 201, in make_runner
    return SynchronousDeferredRunTest(test, test.exception_handlers)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestSynchronousDeferredRunTest.test_setUp_followed_by_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 239, in test_setUp_followed_by_test
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 201, in make_runner
    return SynchronousDeferredRunTest(test, test.exception_handlers)
TypeError: 'NoneType' object is not callable
======================================================================
ERROR: testtools.tests.test_deferredruntest.TestSynchronousDeferredRunTest.test_success
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_deferredruntest.py", line 208, in test_success
    runner = self.make_runner(test)
  File "testtools/tests/test_deferredruntest.py", line 201, in make_runner
    return SynchronousDeferredRunTest(test, test.exception_handlers)
TypeError: 'NoneType' object is not callable
======================================================================
FAIL: testtools.tests.test_spinner.TestRunInReactor.test_clean_delayed_call
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_spinner.py", line 214, in test_clean_delayed_call
    self.assertThat(results, Equals([call]))
  File "testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: !=:
reference = [<twisted.internet.base.DelayedCall instance at 0x7ff6e2985b48>]
actual    = [<twisted.internet.base.DelayedCall instance at 0x7ff6de72da70>,
 <twisted.internet.base.DelayedCall instance at 0x7ff6de72dab8>,
 <twisted.internet.base.DelayedCall instance at 0x7ff6de72db00>,
 <twisted.internet.base.DelayedCall instance at 0x7ff6e2985b48>]

Ran 1196 tests in 0.960s
FAILED (failures=32)
Makefile:7: recipe for target 'check' failed
make: *** [check] Error 1
```

**Comment by warsaw** [comment]
Could it be that on Ubuntu, we have python-twisted-core 15.2.1-1ubuntu1 but no python3-twisted-core, and could it further be caused by _LogObserver no longer being available in twisted.trial.unittest?

**Comment by rbtcollins** [comment]
See #149

**Comment by warsaw** [comment]
Two failures aren't fixed by cjwatson's patch.  I'll open separate issues for those once I've tracked them down (I have one fixed now, looking at the other)
