### ISSUE TITLE
testtools 1.8.0: compile failure and test failures

### ISSUE THREAD

**Issue by tgurr** [testing-cabal/testtools#152]
I've two problems which are kind of related so let me try to explain. testtools-0.5.0 compiles, installs and works fine. However when trying to compile 1.8.0 I run into the following error:

**\* Error compiling '/var/tmp/paludis/build/dev-python-testtools-1.8.0/image//usr/x86_64-pc-linux-gnu/lib/python3.4/site-packages/testtools/_compat2x.py'...
  File "/usr/x86_64-pc-linux-gnu/lib/python3.4/site-packages/testtools/_compat2x.py", line 16
    raise exc_class, exc_obj, exc_tb
                   ^
SyntaxError: invalid syntax

which is also mentioned at https://bugs.launchpad.net/testtools/+bug/953371.

I "solved" this by removing testtools/_compat2x.py for python3 targets (3.3 & 3.4) since it seems testtools-0.5.0 only installed that file for python2 targets as well.

But then other packages using testtools start failing their tests complaining about not being able to find _compat2x.py when running the tests for python3 targets, for example testscenarios:
# [...]
## ERROR: testscenarios.testcase (unittest.loader.ModuleImportFailure)

Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/case.py", line 384, in _executeTestPart
    function()
  File "/usr/lib/python3.3/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: testscenarios.testcase
Traceback (most recent call last):
  File "/usr/lib/python3.3/unittest/loader.py", line 261, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.3/unittest/loader.py", line 239, in _get_module_from_name
    __import__(name)
  File "/var/tmp/paludis/build/dev-python-testscenarios-0.5.0/work/PYTHON_ABIS/3.3/testscenarios-0.5.0/testscenarios/**init**.py", line 58, in <module>
    from testscenarios.scenarios import (
  File "/var/tmp/paludis/build/dev-python-testscenarios-0.5.0/work/PYTHON_ABIS/3.3/testscenarios-0.5.0/testscenarios/scenarios.py", line 33, in <module>
    from testtools.testcase import clone_test_with_new_id
  File "/usr/lib/python3.3/site-packages/testtools/**init**.py", line 59, in <module>
    from testtools.matchers._impl import (
  File "/usr/lib/python3.3/site-packages/testtools/matchers/__init__.py", line 58, in <module>
    from ._basic import (
  File "/usr/lib/python3.3/site-packages/testtools/matchers/_basic.py", line 21, in <module>
    from ..compat import (
  File "/usr/lib/python3.3/site-packages/testtools/compat.py", line 36, in <module>
    from testtools import _compat2x as _compat
ImportError: cannot import name _compat2x
[...]

Any help would be appreciated, for now I've reverted testtools back to 1.5.0 in our distribution which is of course far from any proper solution.

**Comment by rbtcollins** [comment]
What command are you running that fails like that? Failure to byte-compile _compat2x is (correctly) ignored by pip etc and has been for ages.

**Comment by tgurr** [comment]
This are the commands we run for our python packages for each python abi:
```
edo python$(python_get_abi)    -mcompileall -f -q -d $(python_get_libdir) "${excludes[@]}" "${IMAGE}$(python_get_libdir)"
edo python$(python_get_abi) -O -mcompileall -f -q -d $(python_get_libdir) "${excludes[@]}" "${IMAGE}$(python_get_libdir)"
```
And the package manager treats failures as errors and thus stops.

We worked around that problem now by adding _compat2x.py to our PYTHON_BYTECOMPILE_EXCLUDES, thus it won't try to byte-compile it but still install _compat2x.py.

**Comment by jelmer** [comment]
Closing this, since it should no longer be relevant with Python 2 being unsupported.
