### ISSUE TITLE
odd setuptools error

### ISSUE THREAD

**Issue by thomir** [testing-cabal/testtools#153]
While running 'python setup.py develop', I get a number of tracebacks, a 100% pegged CPU, and a MemoryError - fun!

Here's how to reproduce:

1. Create a virtualenv for python 3.4.3 (I haven't tested other versions - they may work as well).
    ```
    virtualenv -p python3 ve3
    . ve3/bin/activate
    ```

2. Install testtools in 'developer mode':
    ```
    python setup.py develop
    ```

When I run this, I get the following output:
```
running develop
running egg_info
writing requirements to testtools.egg-info/requires.txt
writing top-level names to testtools.egg-info/top_level.txt
writing dependency_links to testtools.egg-info/dependency_links.txt
writing testtools.egg-info/PKG-INFO
writing pbr to testtools.egg-info/pbr.json
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no files found matching 'AUTHORS'
warning: no files found matching 'ChangeLog'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc/_build'
writing manifest file 'testtools.egg-info/SOURCES.txt'
running build_ext
Creating /home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/testtools.egg-link (link to .)
testtools 0.9.24.dev253 is already the active version in easy-install.pth

Installed /home/thomi/code/canonical/testtools/testtools
Processing dependencies for testtools==0.9.24.dev253
Searching for traceback2
Reading https://pypi.python.org/simple/traceback2/
Best match: traceback2 1.4.0
Downloading https://pypi.python.org/packages/source/t/traceback2/traceback2-1.4.0.tar.gz#md5=9e9723f4d70bfc6308fa992dd193c400
Processing traceback2-1.4.0.tar.gz
Writing /tmp/easy_install-48ra02iu/traceback2-1.4.0/setup.cfg
Running traceback2-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-48ra02iu/traceback2-1.4.0/egg-dist-tmp-9iq7dwv3
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/util.py", line 245, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config)
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/util.py", line 379, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/__init__.py", line 124, in __init__
    _Command.__init__(self,dist)
  File "/usr/lib/python3.4/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/util.py", line 245, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config)
  File "/home/thomi/code/canonical/testtools/testtools/.eggs/pbr-1.8.0-py3.4.egg/pbr/util.py", line 379, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/__init__.py", line 124, in __init__
    _Command.__init__(self,dist)
  File "/usr/lib/python3.4/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 108, in dump
    return pickle.dumps(type), pickle.dumps(exc)
_pickle.PicklingError: Can't pickle <class 'setuptools.sandbox.UnpickleableException'>: it's not the same object as setuptools.sandbox.UnpickleableException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    pbr=True)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/thomi/code/canonical/testtools/testtools/ve3/lib/python3.4/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
MemoryError
```

The command takes about a minute to complete, and during that time python pegs a CPU core to 100%, and memory usage goes through the roof :(

If `python setup.py develop` isn't supported, we should make it exit immediately with an error. I can't see why we wouldn't support it though, so this is likely 'just a bug'.

**Comment by thomir** [comment]
OK, it turns out this happens for me when invoking any command - including 'install' etc.

**Comment by rbtcollins** [comment]
setup.py install and setup.py develop both trigger easy_install which is ugh. 'pip install .' and 'pip install -e .' are equivalent without this same degree of urgh.

You may need to install pbr first (because of a bug in pbr being worked on atm)

**Comment by thomir** [comment]
Thanks @rbtcollins I'll look at that again today.

Is it worth spending time fixing this? A few different options exist here:

1. At a minimum I think README should have build / develop instructions (I thought there were some, but I couldn't find them?). 

2. Slightly better would be to have setup.py error with 'please run "pip install" instead' if it detected it was being run with easy_install. 

3. Better still would be to find the incompatibility and fix it properly.

I'm more than happy to submit PRs for 1 and 2, if you think it's worth it.

Cheers,

**Comment by rbtcollins** [comment]
doc/hacking.rst is where I'd put such instructions.

I'm not sure we can sanely detect 'run without pip', but I'm not against it if we can. Note that things like build_sphinx will be run without pip.

Good luck on three :)

**Comment by thomir** [comment]
hmmm...

if anyone else said "good luck", I'd take it as a personal challenge. From you though....

I'll take a look at making this more obvious in the docs today (I need some hacktoberfest PRs)

**Comment by thomir** [comment]
Closing this as the instructions above work for me.
