### ISSUE TITLE
multiple test failures in version 1.8.0

### ISSUE THREAD

**Issue by jlec** [testing-cabal/testtools#156]
```python
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_list_failed_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 215, in test_run_list_failed_import
    """, doctest.ELLIPSIS))
  File "testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: Expected:
    Failed to import test module: runexample
    Traceback (most recent call last):
      File ".../loader.py", line ..., in _find_test_path
        package = self._get_module_from_name(name)
      File ".../loader.py", line ..., in _get_module_from_name
        __import__(name)
      File ".../runexample/__init__.py", line 1
        class not in
    ...^...
    SyntaxError: invalid syntax

Got:
    unittest2.loader._FailedTest.runexample
    Failed to import test module: runexample
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/unittest2/loader.py", line 490, in _find_test_path
        package = self._get_module_from_name(name)
      File "/usr/lib64/python2.7/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
        __import__(name)
      File "/var/tmp/portage/dev-python/testtools-1.8.0/temp/tmpE53tLU/runexample/__init__.py", line 1
        class not in
                ^
    SyntaxError: invalid syntax
    <BLANKLINE>

Ran 1196 tests in 0.197s
```
with all python version 2.7 - 3.5

**Comment by rbtcollins** [comment]
How were you testing it? (what specific command did you run?)

**Comment by jlec** [comment]
Like you are doing here https://github.com/testing-cabal/testtools/blob/master/.travis.yml#L44

**Comment by rbtcollins** [comment]
You're running it within travis? How are you installing your dependencies?

**Comment by rbtcollins** [comment]
What versions of the dependencies do you have installed?

**Comment by jlec** [comment]
I using system installed packages, mainly installed using python setup.py install into systems site-dir.

extras-0.0.3
mimeparse-0.1.4
pbr-1.8.1
unittest2-1.1.0
traceback2-1.4.0

**Comment by rbtcollins** [comment]
Hmm, can't find mimeparse 0.1.4 - it has no distributions up on PyPI.

**Comment by rbtcollins** [comment]
```
(test)robertc@lifeless-z140:/tmp/testtools-1.8.0$ pip install extras==0.0.3 mimeparse==0.1.3 pbr unittest2==1.1.0 traceback2==1.4.0
Collecting extras==0.0.3
Collecting mimeparse==0.1.3
  Downloading mimeparse-0.1.3.tar.gz
Collecting pbr
  Using cached pbr-1.8.1-py2.py3-none-any.whl
Collecting unittest2==1.1.0
  Using cached unittest2-1.1.0-py2.py3-none-any.whl
Collecting traceback2==1.4.0
  Using cached traceback2-1.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from unittest2==1.1.0)
Collecting six>=1.4 (from unittest2==1.1.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2==1.4.0)
  Using cached linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: extras, mimeparse, pbr, linecache2, traceback2, six, unittest2
  Running setup.py install for mimeparse
Successfully installed extras-0.0.3 linecache2-1.0.0 mimeparse-0.1.3 pbr-1.8.1 six-1.10.0 traceback2-1.4.0 unittest2-1.1.0
(test)robertc@lifeless-z140:/tmp/testtools-1.8.0$ python -m testtools.run testtools.tests.test_suite
Tests running...
======================================================================
ERROR: testtools.tests.test_testresult.TestStreamToDict.test_bad_mime
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_testresult.py", line 781, in test_bad_mime
    test_id='id')
  File "testtools/testresult/real.py", line 638, in status
    primary, sub, parameters = parse_mime_type(mime_type)
  File "/home/robertc/.virtualenvs/test/local/lib/python2.7/site-packages/mimeparse.py", line 33, in parse_mime_type
    for param in parts[1:] ])
ValueError: dictionary update sequence element #0 has length 3; 2 is required

Ran 1196 tests in 0.179s
FAILED (failures=1)
```

Thats indicative of a bug in mimeparse 0.1.3 I think; trying to find a 0.1.4 tarball to install :/

**Comment by rbtcollins** [comment]
Copied in a version of mimeparse, everything passes:
```
python -m testtools.run testtools.tests.test_suite
Tests running...

Ran 1196 tests in 0.152s
OK
```

So I think you're going to need to diagnose whats broken about your environment a bit more.

**Comment by jlec** [comment]
> Hmm, can't find mimeparse 0.1.4 - it has no distributions up on PyPI.

It's actually [python-mimeparse](https://pypi.python.org/pypi/python-mimeparse).

**Comment by jlec** [comment]
okay, I tried to run it again on my other machine and it works. Closing it for now.
