### ISSUE TITLE
Failed tests with 2.0.0 release

### ISSUE THREAD

**Issue by felixonmars** [testing-cabal/testtools#210]
I am getting the following failed tests with Python 2.7.11, that are not present on the previous 1.9.0 release.

```
Usage: prog discover [options]

prog discover: error: no such option: -l
Usage: prog discover [options]

prog discover: error: no such option: -l
Tests running...
option -l not recognized
Usage: prog [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  prog                               - run default set of tests
  prog MyTestSuite                   - run suite 'MyTestSuite'
  prog MyTestCase.testSomething      - run MyTestCase.testSomething
  prog MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase

option -l not recognized
Usage: prog [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  prog                               - run default set of tests
  prog MyTestSuite                   - run suite 'MyTestSuite'
  prog MyTestCase.testSomething      - run MyTestCase.testSomething
  prog MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase

option -l not recognized
Usage: prog [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  prog                               - run default set of tests
  prog MyTestSuite                   - run suite 'MyTestSuite'
  prog MyTestCase.testSomething      - run MyTestCase.testSomething
  prog MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase

option -l not recognized
Usage: prog [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  prog                               - run default set of tests
  prog MyTestSuite                   - run suite 'MyTestSuite'
  prog MyTestCase.testSomething      - run MyTestCase.testSomething
  prog MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase

option -l not recognized
Usage: prog [options] [test] [...]

Options:
  -h, --help       Show this message
  -v, --verbose    Verbose output
  -q, --quiet      Minimal output
  -f, --failfast   Stop on first failure
  -c, --catch      Catch control-C and display results
  -b, --buffer     Buffer stdout and stderr during test runs

Examples:
  prog                               - run default set of tests
  prog MyTestSuite                   - run suite 'MyTestSuite'
  prog MyTestCase.testSomething      - run MyTestCase.testSomething
  prog MyTestCase                    - run all 'test*' test methods
                                               in MyTestCase

======================================================================
ERROR: testtools.tests.test_distutilscmd.TestCommandTest.test_test_module
----------------------------------------------------------------------
stdout: {{{
Tests running...

Ran 2 tests in 0.001s
OK
}}}

Traceback (most recent call last):
  File "testtools/tests/test_distutilscmd.py", line 66, in test_test_module
    dist.run_command('test')
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "testtools/distutilscmd.py", line 62, in run
    exit=False)
  File "testtools/run.py", line 198, in __init__
    del self.testLoader.errors[:]
AttributeError: 'TestLoader' object has no attribute 'errors'
======================================================================
ERROR: testtools.tests.test_distutilscmd.TestCommandTest.test_test_suite
----------------------------------------------------------------------
stdout: {{{
Tests running...

Ran 2 tests in 0.001s
OK
}}}

Traceback (most recent call last):
  File "testtools/tests/test_distutilscmd.py", line 88, in test_test_suite
    dist.run_command('test')
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "testtools/distutilscmd.py", line 62, in run
    exit=False)
  File "testtools/run.py", line 198, in __init__
    del self.testLoader.errors[:]
AttributeError: 'TestLoader' object has no attribute 'errors'
======================================================================
ERROR: testtools.tests.test_run.TestRun.test_issue_16662
----------------------------------------------------------------------
traceback-1: {{{
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fixtures/fixture.py", line 125, in cleanUp
    return self._cleanups(raise_errors=raise_first)
  File "/usr/lib/python2.7/site-packages/fixtures/callmany.py", line 88, in __call__
    reraise(error[0], error[1], error[2])
  File "/usr/lib/python2.7/site-packages/fixtures/callmany.py", line 82, in __call__
    cleanup(*args, **kwargs)
ValueError: list.remove(x): x not in list
}}}

Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 350, in test_issue_16662
    ['prog', 'discover', '-l', pkg.package.base], out))
  File "testtools/run.py", line 264, in main
    stdout=stdout)
  File "testtools/run.py", line 171, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 113, in parseArgs
    self._do_discovery(argv[2:])
  File "testtools/run.py", line 211, in _do_discovery
    super(TestProgram, self)._do_discovery(argv, Loader=Loader)
  File "/usr/lib/python2.7/unittest/main.py", line 190, in _do_discovery
    options, args = parser.parse_args(argv)
  File "/usr/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/usr/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib/python2.7/optparse.py", line 1574, in exit
    sys.exit(status)
SystemExit: 2
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_custom_list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 157, in test_run_custom_list
    raise AssertionError("-l tried to exit. %r" % exc_info[1])
AssertionError: -l tried to exit. SystemExit(2,)
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 189, in test_run_list
    raise AssertionError("-l tried to exit. %r" % exc_info[1])
AssertionError: -l tried to exit. SystemExit(2,)
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_list_failed_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 216, in test_run_list_failed_import
    """, doctest.ELLIPSIS))
  File "testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: Expected:
    unittest.loader._FailedTest.runexample
    Failed to import test module: runexample
    Traceback (most recent call last):
      File ".../loader.py", line ..., in _find_test_path
        package = self._get_module_from_name(name)
      File ".../loader.py", line ..., in _get_module_from_name
        __import__(name)
      File ".../runexample/__init__.py", line 1
        class not in
    ...^...
    SyntaxError: invalid syntax

Got:
    <BLANKLINE>
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_list_with_loader
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 177, in test_run_list_with_loader
    raise AssertionError("-l tried to exit. %r" % exc_info[1])
AssertionError: -l tried to exit. SystemExit(2,)
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_load_list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 266, in test_run_load_list
    "-l --load-list tried to exit. %r" % exc_info[1])
AssertionError: -l --load-list tried to exit. SystemExit(2,)
======================================================================
FAIL: testtools.tests.test_run.TestRun.test_run_orders_tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_run.py", line 240, in test_run_orders_tests
    "-l --load-list tried to exit. %r" % exc_info[1])
AssertionError: -l --load-list tried to exit. SystemExit(2,)

Ran 2525 tests in 0.618s
FAILED (failures=9)
```

**Comment by jml** [comment]
How are you running the tests?

**Comment by felixonmars** [comment]
I ran it using `python2 -m testtools.run testtools.tests.test_suite`.

Note that the same command with `python2` replaced with `python3` passes all tests (with Python 3.5.1). It also worked with the 1.9.0 release.

**Comment by jml** [comment]
Interesting. That's what our Travis tests run (see https://github.com/testing-cabal/testtools/blob/master/.travis.yml) and they pass just fine. Perhaps there's a missing dependency? Or some environment variable set differently?

**Comment by felixonmars** [comment]
Sorry, I was running the test suite against the python `unittest` standard library, which works for 3.5 but not 2.7 on 2.0.0, which fortunately worked with 1.9.0.
