### ISSUE TITLE
Tests fail with PyPy 6.0.0

### ISSUE THREAD

**Issue by mgorny** [testing-cabal/testtools#274]
Apparently the tests fail again with new PyPy release:

```
$ pypy --version
Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, Apr 26 2018, 20:40:10)
[PyPy 6.0.0 with GCC 6.4.0]
```
```
$ pypy -m testtools.run testtools.tests.test_suite
Tests running...
======================================================================
FAIL: testtools.tests.test_testresult.TestNonAsciiResults.test_syntax_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_testresult.py", line 2688, in test_syntax_error
    ), textoutput)
  File "testtools/testcase.py", line 417, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: '  File "<string>", line 1\n    f(a, b c)\n          ^\nSyntaxError: ' not in u'Tests running...\n======================================================================\nERROR: test_syntax_error.Test.runTest\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/tmp/TestNonAsciiResultswWaKvk/test_syntax_error.py", line 6, in runTest\n    exec (\'f(a, b c)\')\n  File "<string>", line 1\n    f(a, b c)\n           ^\nSyntaxError: invalid syntax (expected \')\')\n\nRan 1 test in 0.004s\nFAILED (failures=1)\n'
======================================================================
FAIL: testtools.tests.test_testresult.TestNonAsciiResultsWithUnittest.test_syntax_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_testresult.py", line 2688, in test_syntax_error
    ), textoutput)
  File "testtools/testcase.py", line 417, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "testtools/testcase.py", line 498, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: '  File "<string>", line 1\n    f(a, b c)\n          ^\nSyntaxError: ' not in 'E\n======================================================================\nERROR: runTest (test_syntax_error.Test)\ntest_syntax_error.Test.runTest\n----------------------------------------------------------------------\n_StringException: Traceback (most recent call last):\n  File "/tmp/TestNonAsciiResultsWithUnittestHrlwXa/test_syntax_error.py", line 6, in runTest\n    exec (\'f(a, b c)\')\n  File "<string>", line 1\n    f(a, b c)\n           ^\nSyntaxError: invalid syntax (expected \')\')\n\n\n----------------------------------------------------------------------\nRan 1 test in 0.002s\n\nFAILED (errors=1)\n'

Ran 2625 tests in 5.474s
FAILED (failures=2)
```

Original report: https://bugs.gentoo.org/654196 (I've confirmed with git master)

**Comment by hugovk** [comment]
This is also now failing on the CI with `master` with PyPy 7.1.1:

```console
$ python --version
Python 2.7.13 (8cdda8b8cdb8, Apr 14 2019, 14:06:44)
[PyPy 7.1.1 with GCC 6.2.0 20160901]
```

```console
$ python -m testtools.run testtools.tests.test_suite
Tests running...
======================================================================
FAIL: testtools.tests.test_testresult.TestNonAsciiResults.test_syntax_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_testresult.py", line 2688, in test_syntax_error
    ), textoutput)
  File "testtools/testcase.py", line 421, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "testtools/testcase.py", line 502, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: '  File "<string>", line 1\n    f(a, b c)\n          ^\nSyntaxError: ' not in u'Tests running...\n======================================================================\nERROR: test_syntax_error.Test.runTest\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/tmp/TestNonAsciiResultsozhszD/test_syntax_error.py", line 6, in runTest\n    exec (\'f(a, b c)\')\n  File "<string>", line 1\n    f(a, b c)\n           ^\nSyntaxError: invalid syntax (expected \')\')\n\nRan 1 test in 0.001s\nFAILED (failures=1)\n'
======================================================================
FAIL: testtools.tests.test_testresult.TestNonAsciiResultsWithUnittest.test_syntax_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testtools/tests/test_testresult.py", line 2688, in test_syntax_error
    ), textoutput)
  File "testtools/testcase.py", line 421, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "testtools/testcase.py", line 502, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: '  File "<string>", line 1\n    f(a, b c)\n          ^\nSyntaxError: ' not in 'E\n======================================================================\nERROR: runTest (test_syntax_error.Test)\ntest_syntax_error.Test.runTest\n----------------------------------------------------------------------\n_StringException: Traceback (most recent call last):\n  File "/tmp/TestNonAsciiResultsWithUnittesthZbAks/test_syntax_error.py", line 6, in runTest\n    exec (\'f(a, b c)\')\n  File "<string>", line 1\n    f(a, b c)\n           ^\nSyntaxError: invalid syntax (expected \')\')\n\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nFAILED (errors=1)\n'
Ran 2625 tests in 2.129s
FAILED (failures=2)
```

https://travis-ci.org/hugovk/testtools/jobs/616217039
