### ISSUE TITLE
New release, with no dependency on unittest2?

### ISSUE THREAD

**Issue by CyrilRoelandteNovance** [testing-cabal/testtools#303]
Hello,

The latest testtools release on PyPI (2.4.0) still requires unittest2. Unittest2 is broken in Python 3.10 (currently an alpha release) because it uses collections.MutableMapping, which is being removed in 3.10. This means that all the projects that somehow depend on testtools cannot run their tests using Python 3.10. For instance, this is what I get when running the tests for pbr (which depends on testrepository, which depends on subunit, which depends on testtools):

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vagrant/pbr/setup.py", line 18, in <module>
        from pbr import util
      File "/home/vagrant/pbr/pbr/util.py", line 85, in <module>
        import pbr.hooks
      File "/home/vagrant/pbr/pbr/hooks/__init__.py", line 16, in <module>
        from pbr.hooks import backwards
      File "/home/vagrant/pbr/pbr/hooks/backwards.py", line 17, in <module>
        from pbr import packaging
      File "/home/vagrant/pbr/pbr/packaging.py", line 55, in <module>
        from pbr import testr_command
      File "/home/vagrant/pbr/pbr/testr_command.py", line 162, in <module>
        from testrepository import commands
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/testrepository/commands/__init__.py", line 40, in <module>
        import subunit
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/subunit/__init__.py", line 130, in <module>
        from testtools import content, content_type, ExtendedToOriginalDecorator
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/testtools/__init__.py", line 71, in <module>
        from testtools.testcase import (
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/testtools/testcase.py", line 33, in <module>
        import unittest2 as unittest
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/loader.py", line 13, in <module>
        from unittest2 import case, suite, util
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/case.py", line 18, in <module>
        from unittest2 import result
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/result.py", line 10, in <module>
        from unittest2.compatibility import wraps
      File "/home/vagrant/pbr/.tox/py310/lib/python3.10/site-packages/unittest2/compatibility.py", line 143, in <module>
        class ChainMap(collections.MutableMapping):
    AttributeError: module 'collections' has no attribute 'MutableMapping'

```

Removing unittest2 from the venv allows me to run the tests.

Python 3.10 should be released in October (see the [release schedule](https://www.python.org/dev/peps/pep-0619/)). The current master branch of testtools does not require unittest2. Would it be possible to get a new testtools release before then?

**Comment by kloczek** [comment]
+1

**Comment by mtreinish** [comment]
2.50 is up on pypi now https://pypi.org/project/testtools/2.5.0/
