### ISSUE TITLE
Failing tests under Python 3.13

### ISSUE THREAD

**Issue by thomasgoirand** [testing-cabal/testtools#400]
Hi,

As per this bug report:
https://bugs.debian.org/1082273

testtool fails 2 unit tests under Python 3.13:

```
======================================================================
FAIL: testtools.tests.twistedsupport.test_runtest.TestAsynchronousDeferredRunTest.test_log_in_details
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/testtools/tests/twistedsupport/test_runtest.py", line 743, in test_log_in_details
    self.assertThat(
    ~~~~~~~~~~~~~~~^
        result._events,
        ^^^^^^^^^^^^^^^
    ...<11 lines>...
        ),
        ^^
    )
    ^
  File "/<<PKGBUILDDIR>>/testtools/testcase.py", line 509, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: Differences: [
Differences: [
Differences: {
  'twisted-log': '''\
2024-09-19 08:49:38+0000 [-] foo
2024-09-19 08:49:38+0000 [-] Main loop terminated.
''' does not end with '''\
 foo
'''.: after <function <lambda>> on <Content type=text/plain; charset="utf8", value=b'2024-09-19 08:49:38+0000 [-] foo\n2024-09-19 08:49:38+0000 [-] Main loop terminated.\n'>,
}
]
]
======================================================================
FAIL: testtools.tests.twistedsupport.test_runtest.TestAsynchronousDeferredRunTest.test_log_to_twisted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/testtools/tests/twistedsupport/test_runtest.py", line 792, in test_log_to_twisted
    self.assertThat(
    ~~~~~~~~~~~~~~~^
        messages, MatchesListwise([ContainsDict({"message": Equals(("foo",))})])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/<<PKGBUILDDIR>>/testtools/testcase.py", line 509, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: Differences: [
len([{'system': '-', 'message': ('foo',), 'time': 1726735778.9094028, 'isError': 0, 'log_time': 1726735778.9094028, 'log_text': 'foo', 'log_format': '{log_text}', 'log_level': <LogLevel=info>, 'log_namespace': 'log_legacy', 'log_system': '-', 'format': '%(log_legacy)s', 'log_legacy': <twisted.logger._stdlib.StringifiableFromEvent object at 0xffff854cec10>}, {'log_logger': <Logger 'twisted.internet.base'>, 'log_level': <LogLevel=info>, 'log_namespace': 'twisted.internet.base', 'log_source': None, 'log_format': 'Main loop terminated.', 'log_time': 1726735778.909665, 'message': (), 'time': 1726735778.909665, 'system': '-', 'format': '%(log_legacy)s', 'log_legacy': <twisted.logger._stdlib.StringifiableFromEvent object at 0xffff854ced50>, 'isError': 0}]) != 1: Length mismatch
]

Ran 2627 tests in 1.530s
FAILED (failures=2)

```
Please help me to fix them before Python 3.13 becomes available in Debian Unstable.

**Comment by cjwatson** [comment]
Stefano confirmed my suspicion in https://bugs.debian.org/1082273.  Closing.
